
- hosts: control, compute
  become: true

  tasks:
  - name: Comment out cc-subnet1 hosts entries (10.0.1.*)
    lineinfile:
      path: /etc/hosts
      regexp: '^10.0.1.*'
      backup: yes
      firstmatch: yes
      line: '#'
      backrefs: yes

  - name: Comment out cc-subnet2 hosts entries (10.0.2.*)
    lineinfile:
      path: /etc/hosts
      regexp: '^10.0.2.*'
      backup: yes
      firstmatch: yes
      line: '#'
      backrefs: yes
